// First Name	100	VARCHAR(100)
// Last Name	100	VARCHAR(100)
// Email	254	VARCHAR(254)
// Phone	20	VARCHAR(20)
// Address 1	255	VARCHAR(255)
// Address 2	255	VARCHAR(255)
// City	100	VARCHAR(100)
// State	20	VARCHAR(20)
// ZIP	10	VARCHAR(10)
// Email Body	2000	TEXT



// real structure
const fakeLegislators = [
  {
    ID: "19a6f560-e9c5-4cf2-bd70-6af17471be31",
    name: "Kevin Alons",
    title: null,
    firstName: "Kevin",
    middleName: null,
    lastName: "Alons",
    email: "kevin.alons@mailinator.com",
    district: "7",
    county: "Woodbury",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "154859f0-7805-4424-9fd8-d0301cfc0b79",
    name: "Jerome Amos Jr.",
    title: null,
    firstName: "Jerome",
    middleName: null,
    lastName: "Amos Jr.",
    email: "jerome.amosjr@mailinator.com",
    district: "62",
    county: "Black Hawk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "30624743-ccce-4863-a88b-edf5d4432c43",
    name: "Eddie Andrews",
    title: null,
    firstName: "Eddie",
    middleName: null,
    lastName: "Andrews",
    email: "eddie.andrews@mailinator.com",
    district: "43",
    county: "Polk",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "5db31514-1c0d-4086-af49-88557369a229",
    name: "Austin Baeth",
    title: null,
    firstName: "Austin",
    middleName: null,
    lastName: "Baeth",
    email: "austin.baeth@mailinator.com",
    district: "36",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "68b9df96-7ccb-4c65-adc2-5c63d1365c18",
    name: "Sean Bagniewski",
    title: null,
    firstName: "Sean",
    middleName: null,
    lastName: "Bagniewski",
    email: "sean.bagniewski@mailinator.com",
    district: "35",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "32622a4f-e84d-4536-89e9-21c12c531fe9",
    name: "Brett Barker",
    title: null,
    firstName: "Brett",
    middleName: null,
    lastName: "Barker",
    email: "brett.barker@mailinator.com",
    district: "51",
    county: "Story",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "0c8bbc27-c99b-47fa-b22a-4a5c6af86e41",
    name: "Chad Behn",
    title: null,
    firstName: "Chad",
    middleName: null,
    lastName: "Behn",
    email: "chad.behn@mailinator.com",
    district: "48",
    county: "Boone",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "e18e0acf-590b-43a5-b69b-c8f6862515e2",
    name: "Liz Bennett",
    title: null,
    firstName: "Liz",
    middleName: null,
    lastName: "Bennett",
    email: "liz.bennett@mailinator.com",
    district: "39",
    county: "Linn",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "a0a236b8-864e-431b-aa91-0c60085b1b22",
    name: "Michael R. Bergan",
    title: null,
    firstName: "Michael",
    middleName: "R.",
    lastName: "Bergan",
    email: "michael.bergan@mailinator.com",
    district: "63",
    county: "Winneshiek",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "aae65b23-9ac6-4b82-bc14-43f1063259f6",
    name: "Tony Bisignano",
    title: null,
    firstName: "Tony",
    middleName: null,
    lastName: "Bisignano",
    email: "tony.bisignano@mailinator.com",
    district: "15",
    county: "Polk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "05b4d69e-df01-4f10-8ee6-ce584e801908",
    name: "Matt Blake",
    title: null,
    firstName: "Matt",
    middleName: null,
    lastName: "Blake",
    email: "matt.blake@mailinator.com",
    district: "22",
    county: "Polk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "c4fc296a-4269-4c72-98b8-23d9f2894113",
    name: "David L. Blom",
    title: null,
    firstName: "David",
    middleName: "L.",
    lastName: "Blom",
    email: "david.blom@mailinator.com",
    district: "52",
    county: "Marshall",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "2e8177ea-f523-4e3a-b2f5-eef5e7026867",
    name: "Jane Bloomingdale",
    title: null,
    firstName: "Jane",
    middleName: null,
    lastName: "Bloomingdale",
    email: "jane.bloomingdale@mailinator.com",
    district: "60",
    county: "Worth",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "985d5bab-628f-4f56-bb3c-d6cddb28203c",
    name: "Brooke Boden",
    title: null,
    firstName: "Brooke",
    middleName: null,
    lastName: "Boden",
    email: "brooke.boden@mailinator.com",
    district: "21",
    county: "Warren",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "5fe4293c-34ce-4ab4-91d0-5b70ba6e43da",
    name: "Jacob Bossman",
    title: null,
    firstName: "Jacob",
    middleName: null,
    lastName: "Bossman",
    email: "jacob.bossman@mailinator.com",
    district: "14",
    county: "Woodbury",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "6c197f42-2af3-4904-9036-b4110bf13a69",
    name: "Mike Bousselot",
    title: null,
    firstName: "Mike",
    middleName: null,
    lastName: "Bousselot",
    email: "mike.bousselot@mailinator.com",
    district: "21",
    county: "Polk",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "a4941864-e8c2-497a-9974-229409ee9d2f",
    name: "Dr. Steven P. Bradley",
    title: "Dr.",
    firstName: "Steven",
    middleName: "P.",
    lastName: "Bradley",
    email: "steven.bradley@mailinator.com",
    district: "66",
    county: "Jones",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "132d4f31-5961-40f7-8828-c20e1c533b39",
    name: "Timi M. Brown-Powers",
    title: null,
    firstName: "Timi",
    middleName: "M.",
    lastName: "Brown-Powers",
    email: "timi.brown-powers@mailinator.com",
    district: "61",
    county: "Black Hawk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "7f486785-a192-482c-86e4-24a9b16b5bd8",
    name: "Doug Campbell",
    title: null,
    firstName: "Doug",
    middleName: null,
    lastName: "Campbell",
    email: "doug.campbell@mailinator.com",
    district: "30",
    county: "Cerro Gordo",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "309f25dc-8e8b-49fe-af23-61cc27277635",
    name: "Claire Celsi",
    title: null,
    firstName: "Claire",
    middleName: null,
    lastName: "Celsi",
    email: "claire.celsi@mailinator.com",
    district: "16",
    county: "Polk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "822803f7-8725-4267-937a-7e5e76e9ea5a",
    name: "Mark Cisneros",
    title: null,
    firstName: "Mark",
    middleName: null,
    lastName: "Cisneros",
    email: "mark.cisneros@mailinator.com",
    district: "96",
    county: "Muscatine",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "5309cef8-51e9-432d-81d5-358ae4d1ebad",
    name: "Taylor R. Collins",
    title: null,
    firstName: "Taylor",
    middleName: "R.",
    lastName: "Collins",
    email: "taylor.collins@mailinator.com",
    district: "95",
    county: "Des Moines",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "c1cb8c12-2f5a-4834-963c-cab4eaa79ad7",
    name: "Jeff Cooling",
    title: null,
    firstName: "Jeff",
    middleName: null,
    lastName: "Cooling",
    email: "jeff.cooling@mailinator.com",
    district: "77",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "e55405a3-6364-4a71-beff-581ba24822de",
    name: "Mark Costello",
    title: null,
    firstName: "Mark",
    middleName: null,
    lastName: "Costello",
    email: "mark.costello@mailinator.com",
    district: "8",
    county: "Mills",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "fca86547-b263-44e1-ae44-57ad5d5b6d2e",
    name: "Ken Croken",
    title: null,
    firstName: "Ken",
    middleName: null,
    lastName: "Croken",
    email: "ken.croken@mailinator.com",
    district: "97",
    county: "Scott",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "74589dc0-9a1e-4a93-8055-2edb3f075561",
    name: "Dan Dawson",
    title: null,
    firstName: "Dan",
    middleName: null,
    lastName: "Dawson",
    email: "dan.dawson@mailinator.com",
    district: "10",
    county: "Pottawattamie",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "d958575f-02c5-4e33-8c0d-7ab944e547c3",
    name: "Tom Determann",
    title: null,
    firstName: "Tom",
    middleName: null,
    lastName: "Determann",
    email: "tom.determann@mailinator.com",
    district: "69",
    county: "Clinton",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "f0f06a8f-09fd-43db-bbfb-4212b6deebf2",
    name: "Adrian Dickey",
    title: null,
    firstName: "Adrian",
    middleName: null,
    lastName: "Dickey",
    email: "adrian.dickey@mailinator.com",
    district: "44",
    county: "Jefferson",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "f7c5684c-2596-4cc9-b8b3-f71e69286e17",
    name: "Zach Dieken",
    title: null,
    firstName: "Zach",
    middleName: null,
    lastName: "Dieken",
    email: "zachary.dieken@mailinator.com",
    district: "5",
    county: "O’Brien",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "13c24ac4-7e46-4cc3-9e65-51e641b44a52",
    name: "Molly Donahue",
    title: null,
    firstName: "Molly",
    middleName: null,
    lastName: "Donahue",
    email: "molly.donahue@mailinator.com",
    district: "37",
    county: "Linn",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "2f544e00-193f-4b03-a12a-3fb53e3c38b6",
    name: "William A. Dotzler Jr.",
    title: null,
    firstName: "William",
    middleName: "A.",
    lastName: "Dotzler Jr.",
    email: "bill.dotzler@mailinator.com",
    district: "31",
    county: "Black Hawk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "faa18d8f-4d8a-48c4-b1f8-ad1b6ca7007b",
    name: "Dawn Driscoll",
    title: null,
    firstName: "Dawn",
    middleName: null,
    lastName: "Driscoll",
    email: "dawn.driscoll@mailinator.com",
    district: "46",
    county: "Iowa",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "0661a579-d85b-467a-a4d7-0c9162aab406",
    name: "Jon Dunwell",
    title: null,
    firstName: "Jon",
    middleName: null,
    lastName: "Dunwell",
    email: "jon.dunwell@mailinator.com",
    district: "38",
    county: "Jasper",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "36915a91-8707-45e3-974e-7447962e7d5a",
    name: "Tracy A. Ehlert",
    title: null,
    firstName: "Tracy",
    middleName: "A.",
    lastName: "Ehlert",
    email: "tracy.ehlert@mailinator.com",
    district: "79",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "b6e37996-2a69-42b0-bb71-91faa01b060e",
    name: "Lynn Evans",
    title: null,
    firstName: "Lynn",
    middleName: null,
    lastName: "Evans",
    email: "lynn.evans@mailinator.com",
    district: "3",
    county: "Cherokee",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "382861a0-7682-4b7d-92de-50969ea76aa2",
    name: "Samantha Fett",
    title: null,
    firstName: "Samantha",
    middleName: null,
    lastName: "Fett",
    email: "samantha.fett@mailinator.com",
    district: "22",
    county: "Warren",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "b30f7235-e67e-4669-9da2-95f897eacd25",
    name: "Dean Fisher",
    title: null,
    firstName: "Dean",
    middleName: null,
    lastName: "Fisher",
    email: "dean.fisher@mailinator.com",
    district: "53",
    county: "Tama",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "2cf48ea9-a099-451c-8cba-c5d6e676b845",
    name: "Ruth Ann Gaines",
    title: null,
    firstName: "Ruth",
    middleName: "Ann",
    lastName: "Gaines",
    email: "ruthann.gaines@mailinator.com",
    district: "33",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "93996545-c4fc-410c-bce2-1a880b539f88",
    name: "Julian B. Garrett",
    title: null,
    firstName: "Julian",
    middleName: "B.",
    lastName: "Garrett",
    email: "julian.garrett@mailinator.com",
    district: "11",
    county: "Warren",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "085bf394-f2ff-44c0-81a9-1bea26ec0535",
    name: "Sarah Trone Garriott",
    title: null,
    firstName: "Sarah",
    middleName: "Trone",
    lastName: "Garriott",
    email: "sarah.trone.garriott@mailinator.com",
    district: "14",
    county: "Dallas",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "eb34f21d-5833-43d7-83fd-3fb4d083ef96",
    name: "Jason Gearhart",
    title: null,
    firstName: "Jason",
    middleName: null,
    lastName: "Gearhart",
    email: "jason.gearhart@mailinator.com",
    district: "64",
    county: "Clayton",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "b03cdfb0-3553-44b9-bf33-df3b726dcbd6",
    name: "Dan Gehlbach",
    title: null,
    firstName: "Dan",
    middleName: null,
    lastName: "Gehlbach",
    email: "dan.gehlbach@mailinator.com",
    district: "46",
    county: "Dallas",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "7a62b4d9-332c-4709-a512-f7f3dc42a4b8",
    name: "Thomas Gerhold",
    title: null,
    firstName: "Thomas",
    middleName: null,
    lastName: "Gerhold",
    email: "thomas.gerhold@mailinator.com",
    district: "84",
    county: "Benton",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "0bf4f7ec-cab8-435f-be7b-0a648dc6b81e",
    name: "Eric J. Gjerde",
    title: null,
    firstName: "Eric",
    middleName: "J.",
    lastName: "Gjerde",
    email: "eric.gjerde@mailinator.com",
    district: "74",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "f94079db-3fb2-4812-b681-67ecf1ba80b2",
    name: "Cindy Golding",
    title: null,
    firstName: "Cindy",
    middleName: null,
    lastName: "Golding",
    email: "cindy.golding@mailinator.com",
    district: "83",
    county: "Linn",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "c56238da-b395-4593-8083-23fbcc6191f4",
    name: "Daniel Gosa",
    title: null,
    firstName: "Daniel",
    middleName: null,
    lastName: "Gosa",
    email: "daniel.gosa@mailinator.com",
    district: "81",
    county: "Scott",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "c62e867f-e7f2-43ba-b505-f48c4cb47210",
    name: "Pat Grassley",
    title: null,
    firstName: "Pat",
    middleName: null,
    lastName: "Grassley",
    email: "pat.grassley@mailinator.com",
    district: "57",
    county: "Butler",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "585698c0-99c4-4691-85e1-b7c252c0decb",
    name: "Jesse Green",
    title: null,
    firstName: "Jesse",
    middleName: null,
    lastName: "Green",
    email: "jesse.green@mailinator.com",
    district: "24",
    county: "Boone",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "6e21064e-36a3-4ede-94df-5ff1c5f86c2b",
    name: "Kerry Gruenhagen",
    title: null,
    firstName: "Kerry",
    middleName: null,
    lastName: "Gruenhagen",
    email: "kerry.gruenhagen@mailinator.com",
    district: "41",
    county: "Scott",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "9cf57c00-1aae-4802-a76e-4cca1ff9c9f5",
    name: "Bill Gustoff",
    title: null,
    firstName: "Bill",
    middleName: null,
    lastName: "Gustoff",
    email: "bill.gustoff@mailinator.com",
    district: "40",
    county: "Polk",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "20785417-2c0e-4791-a6bb-9553dc64efcb",
    name: "Dennis Guth",
    title: null,
    firstName: "Dennis",
    middleName: null,
    lastName: "Guth",
    email: "dennis.guth@mailinator.com",
    district: "28",
    county: "Hancock",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "0e3ee376-22cf-4b4a-9df3-eeb5e5f0454e",
    name: "Austin Harris",
    title: null,
    firstName: "Austin",
    middleName: null,
    lastName: "Harris",
    email: "austin.harris@mailinator.com",
    district: "26",
    county: "Appanoose",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "671d88d0-5105-44d9-8632-e0dc743a719a",
    name: "Helena Hayes",
    title: null,
    firstName: "Helena",
    middleName: null,
    lastName: "Hayes",
    email: "helena.hayes@mailinator.com",
    district: "88",
    county: "Mahaska",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "88075292-44fe-4145-9641-a4d81a2181c8",
    name: "Bob Henderson",
    title: null,
    firstName: "Bob",
    middleName: null,
    lastName: "Henderson",
    email: "robert.henderson@mailinator.com",
    district: "2",
    county: "Woodbury",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "0865d8fb-b45e-41f8-bbe8-ea72ffa5d7cb",
    name: "Christian A. Hermanson",
    title: null,
    firstName: "Christian",
    middleName: "A.",
    lastName: "Hermanson",
    email: "christian.hermanson@mailinator.com",
    district: "59",
    county: "Cerro Gordo",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "68707115-04c2-4eb5-830c-8bedcfdd8064",
    name: "Steven C. Holt",
    title: null,
    firstName: "Steven",
    middleName: "C.",
    lastName: "Holt",
    email: "steven.holt@mailinator.com",
    district: "12",
    county: "Crawford",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "6283910a-0f20-456f-93da-39ed77771949",
    name: "Heather Hora",
    title: null,
    firstName: "Heather",
    middleName: null,
    lastName: "Hora",
    email: "heather.hora@mailinator.com",
    district: "92",
    county: "Washington",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "45d62217-8d49-44ac-958d-ee4d3b17d573",
    name: "Chad Ingels",
    title: null,
    firstName: "Chad",
    middleName: null,
    lastName: "Ingels",
    email: "chad.ingels@mailinator.com",
    district: "68",
    county: "Fayette",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "02efe7b9-358f-4aec-88f8-d63c5a51eec7",
    name: "David Jacoby",
    title: null,
    firstName: "David",
    middleName: null,
    lastName: "Jacoby",
    email: "david.jacoby@mailinator.com",
    district: "86",
    county: "Johnson",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "7bb6655c-d0db-438e-820f-66ff0b7e8383",
    name: "Lindsay James",
    title: null,
    firstName: "Lindsay",
    middleName: null,
    lastName: "James",
    email: "lindsay.james@mailinator.com",
    district: "71",
    county: "Dubuque",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "37072e16-6acf-443d-af8a-e112e8ea0b0d",
    name: "Thomas M. Jeneary",
    title: null,
    firstName: "Thomas",
    middleName: "M.",
    lastName: "Jeneary",
    email: "tom.jeneary@mailinator.com",
    district: "3",
    county: "Plymouth",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "d2b2abe0-65c3-432c-8241-e49df16d0489",
    name: "Rob Johnson",
    title: null,
    firstName: "Rob",
    middleName: null,
    lastName: "Johnson",
    email: "rob.johnson@mailinator.com",
    district: "34",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "c1f382fd-7571-43bc-9dff-52e0c2088e38",
    name: "Craig P. Johnson",
    title: null,
    firstName: "Craig",
    middleName: "P.",
    lastName: "Johnson",
    email: "craig.johnson@mailinator.com",
    district: "67",
    county: "Buchanan",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "6ab51775-f7e9-460e-86d4-92764ca02fc1",
    name: "Megan Jones",
    title: null,
    firstName: "Megan",
    middleName: null,
    lastName: "Jones",
    email: "megan.jones@mailinator.com",
    district: "6",
    county: "Clay",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "2513d57f-1304-4e0b-9d06-e9d61a82d4e2",
    name: "Kenan Judge",
    title: null,
    firstName: "Kenan",
    middleName: null,
    lastName: "Judge",
    email: "kenan.judge@mailinator.com",
    district: "27",
    county: "Dallas",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "fa11137b-2888-4f77-ba92-b9445aa9c228",
    name: "Bobby Kaufmann",
    title: null,
    firstName: "Bobby",
    middleName: null,
    lastName: "Kaufmann",
    email: "bobby.kaufmann@mailinator.com",
    district: "82",
    county: "Cedar",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "2f027619-13cf-41a3-902f-b52159cb3edc",
    name: "Mike Klimesh",
    title: null,
    firstName: "Mike",
    middleName: null,
    lastName: "Klimesh",
    email: "mike.klimesh@mailinator.com",
    district: "32",
    county: "Winneshiek",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "377a42f4-936a-40f8-b7e6-51b08ab68f37",
    name: "Izaah Knox",
    title: null,
    firstName: "Izaah",
    middleName: null,
    lastName: "Knox",
    email: "izaah.knox@mailinator.com",
    district: "17",
    county: "Polk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "d2d38617-cc70-4dfa-aaa8-6d4959f5f30a",
    name: "Carrie Koelker",
    title: null,
    firstName: "Carrie",
    middleName: null,
    lastName: "Koelker",
    email: "carrie.koelker@mailinator.com",
    district: "33",
    county: "Dubuque",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "b162ee9a-eae4-4327-bb03-6fab51f724f5",
    name: "Jennifer Konfrst",
    title: null,
    firstName: "Jennifer",
    middleName: null,
    lastName: "Konfrst",
    email: "jennifer.konfrst@mailinator.com",
    district: "32",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "253ea0ea-600c-4520-945e-13bdc93c354d",
    name: "Tim Kraayenbrink",
    title: null,
    firstName: "Tim",
    middleName: null,
    lastName: "Kraayenbrink",
    email: "tim.kraayenbrink@mailinator.com",
    district: "4",
    county: "Webster",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "6fc985bc-d394-43ca-84c9-813bc2251eb3",
    name: "Bob Kressig",
    title: null,
    firstName: "Bob",
    middleName: null,
    lastName: "Kressig",
    email: "bob.kressig@mailinator.com",
    district: "75",
    county: "Black Hawk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "c38fa459-8eea-4247-9bca-3309f264e0bb",
    name: "Monica Kurth",
    title: null,
    firstName: "Monica",
    middleName: null,
    lastName: "Kurth",
    email: "monica.kurth@mailinator.com",
    district: "98",
    county: "Scott",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "8287017c-b426-4151-a29c-0de40de51cdd",
    name: "Shannon Latham",
    title: null,
    firstName: "Shannon",
    middleName: null,
    lastName: "Latham",
    email: "shannon.latham@mailinator.com",
    district: "55",
    county: "Franklin",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "7dcd500c-e951-4759-83c3-c961ee8149b2",
    name: "Judd Lawler",
    title: null,
    firstName: "Judd",
    middleName: null,
    lastName: "Lawler",
    email: "judd.lawler@mailinator.com",
    district: "91",
    county: "Johnson",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "2243d09c-7f93-45da-a519-d9b5379509b1",
    name: "Mr. Bryan Lee (Internal Test)",
    title: "Mr.",
    firstName: "Bryan",
    middleName: null,
    lastName: "Lee (Internal Test)",
    email: "bryan@mailinator.com",
    district: "1",
    county: "Adair",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "1a5f8904-4b24-4819-920d-c50366439d3f",
    name: "Elinor A. Levin",
    title: null,
    firstName: "Elinor",
    middleName: "A.",
    lastName: "Levin",
    email: "elinor.levin@mailinator.com",
    district: "89",
    county: "Johnson",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "3ecbef98-3584-4778-98cd-479578973f57",
    name: "Mark S. Lofgren",
    title: null,
    firstName: "Mark",
    middleName: "S.",
    lastName: "Lofgren",
    email: "mark.lofgren@mailinator.com",
    district: "48",
    county: "Muscatine",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "3bcadc85-0c65-4fe3-ac3a-353e024a5a63",
    name: "Brian K. Lohse",
    title: null,
    firstName: "Brian",
    middleName: "K.",
    lastName: "Lohse",
    email: "brian.lohse@mailinator.com",
    district: "45",
    county: "Polk",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "fafc9e16-5579-477b-b381-45cfdf4c18d5",
    name: "Shannon Lundgren",
    title: null,
    firstName: "Shannon",
    middleName: null,
    lastName: "Lundgren",
    email: "shannon.lundgren@mailinator.com",
    district: "65",
    county: "Dubuque",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "fa778297-7c10-4c5c-a5ce-7cad36586218",
    name: "Mary Lee Madison",
    title: null,
    firstName: "Mary",
    middleName: "Lee",
    lastName: "Madison",
    email: "mary.madison@mailinator.com",
    district: "31",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "aae8d83f-b934-48e7-9af8-7d6085b119fd",
    name: "Heather Matson",
    title: null,
    firstName: "Heather",
    middleName: null,
    lastName: "Matson",
    email: "heather.matson@mailinator.com",
    district: "42",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "ca74de8d-1033-429d-9892-f9735910cdc2",
    name: "Larry McBurney",
    title: null,
    firstName: "Larry",
    middleName: null,
    lastName: "McBurney",
    email: "larry.mcburney@mailinator.com",
    district: "44",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "59d48b93-e08a-4903-8e48-5a92d85cd5f3",
    name: "Charlie McClintock",
    title: null,
    firstName: "Charlie",
    middleName: null,
    lastName: "McClintock",
    email: "charlie.mcclintock@mailinator.com",
    district: "42",
    county: "Linn",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "b6614fa2-027a-4051-aa74-6e8f5c01b463",
    name: "Barb Kniff McCulla",
    title: null,
    firstName: "Barb",
    middleName: "Kniff",
    lastName: "McCulla",
    email: "barb.kniffmcculla@mailinator.com",
    district: "37",
    county: "Marion",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "3652905d-6b15-49c4-a9f1-3b7e3c17fc41",
    name: "Joshua Meggers",
    title: null,
    firstName: "Joshua",
    middleName: null,
    lastName: "Meggers",
    email: "joshua.meggers@mailinator.com",
    district: "54",
    county: "Grundy",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "d664cc17-fa61-4eb8-b3dd-079571fdd4b4",
    name: "Brian Meyer",
    title: null,
    firstName: "Brian",
    middleName: null,
    lastName: "Meyer",
    email: "brian.meyer@mailinator.com",
    district: "29",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "46d50480-b921-42a6-8537-4fb51df6c8fb",
    name: "Ann Meyer",
    title: null,
    firstName: "Ann",
    middleName: null,
    lastName: "Meyer",
    email: "ann.meyer@mailinator.com",
    district: "8",
    county: "Webster",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "d579838e-f4f9-45e4-9b0c-08e3dad69ede",
    name: "Gary M. Mohr",
    title: null,
    firstName: "Gary",
    middleName: "M.",
    lastName: "Mohr",
    email: "gary.mohr@mailinator.com",
    district: "93",
    county: "Scott",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "fa8cedee-cba9-4397-afcd-7a8a38f76f19",
    name: "Norlin G. Mommsen",
    title: null,
    firstName: "Norlin",
    middleName: "G.",
    lastName: "Mommsen",
    email: "norlin.mommsen@mailinator.com",
    district: "70",
    county: "Clinton",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "8bff16e6-2296-4c77-b5a3-0ce503021c45",
    name: "Thomas Jay Moore",
    title: null,
    firstName: "Thomas",
    middleName: "Jay",
    lastName: "Moore",
    email: "tom.moore@mailinator.com",
    district: "18",
    county: "Cass",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "3a0e02f6-77a8-4189-b2f0-7093b1cdb384",
    name: "Amy Nielsen",
    title: null,
    firstName: "Amy",
    middleName: null,
    lastName: "Nielsen",
    email: "amy.nielsen@mailinator.com",
    district: "85",
    county: "Johnson",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "680223ee-d27f-4e08-b82f-b312c14bf8f2",
    name: "Carter F. Nordman",
    title: null,
    firstName: "Carter",
    middleName: "F.",
    lastName: "Nordman",
    email: "carter.nordman@mailinator.com",
    district: "47",
    county: "Dallas",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "30f5e0e1-1ae6-49dd-923f-18ab1496da95",
    name: "Rick L. Olson",
    title: null,
    firstName: "Rick",
    middleName: "L.",
    lastName: "Olson",
    email: "rick.olson@mailinator.com",
    district: "39",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "59928b4f-d1bd-400c-80c6-91ffce2431d8",
    name: "Janet Petersen",
    title: null,
    firstName: "Janet",
    middleName: null,
    lastName: "Petersen",
    email: "janet.petersen@mailinator.com",
    district: "18",
    county: "Polk",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "8e3837a9-7fbd-471f-adeb-d15564eefe33",
    name: "Mike Pike",
    title: null,
    firstName: "Mike",
    middleName: null,
    lastName: "Pike",
    email: "mike.pike@mailinator.com",
    district: "20",
    county: "Polk",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "53939ade-11e2-4456-b053-27a916f4104d",
    name: "Herman C. Quirmbach",
    title: null,
    firstName: "Herman",
    middleName: "C.",
    lastName: "Quirmbach",
    email: "herman.quirmbach@mailinator.com",
    district: "25",
    county: "Story",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "72bc7e6f-876f-499d-b4e3-1f152adbe06c",
    name: "Angel Ramirez",
    title: null,
    firstName: "Angel",
    middleName: null,
    lastName: "Ramirez",
    email: "angel.ramirez@mailinator.com",
    district: "78",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "a9f97ed8-dd75-4e1d-b6c7-f14c3ae73d9c",
    name: "Jeff Reichman",
    title: null,
    firstName: "Jeff",
    middleName: null,
    lastName: "Reichman",
    email: "jeff.reichman@mailinator.com",
    district: "50",
    county: "Lee",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "c7a9ae94-b07a-42a6-a623-a94c7732275e",
    name: "Matthew Rinker",
    title: null,
    firstName: "Matthew",
    middleName: null,
    lastName: "Rinker",
    email: "matthew.rinker@mailinator.com",
    district: "99",
    county: "Des Moines",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "107b9691-e846-4dbc-87bf-4f6e4bef4478",
    name: "David D. Rowley",
    title: null,
    firstName: "David",
    middleName: "D.",
    lastName: "Rowley",
    email: "david.rowley@mailinator.com",
    district: "5",
    county: "Dickinson",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "c6a382f5-0e7a-4dc4-9108-7d09ef78ee51",
    name: "Ken Rozenboom",
    title: null,
    firstName: "Ken",
    middleName: null,
    lastName: "Rozenboom",
    email: "ken.rozenboom@mailinator.com",
    district: "19",
    county: "Marion",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "cc890ba6-55d6-44d5-b722-b626a97f781f",
    name: "Sandy Salmon",
    title: null,
    firstName: "Sandy",
    middleName: null,
    lastName: "Salmon",
    email: "sandy.salmon@mailinator.com",
    district: "29",
    county: "Bremer",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "465a4856-00b8-40b8-8f71-893d8a557686",
    name: "J.D. Scholten",
    title: null,
    firstName: "J.D.",
    middleName: null,
    lastName: "Scholten",
    email: "j.d.scholten@mailinator.com",
    district: "1",
    county: "Woodbury",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "6d95b3d4-4438-44f0-925f-453f83ec56d8",
    name: "Jason Schultz",
    title: null,
    firstName: "Jason",
    middleName: null,
    lastName: "Schultz",
    email: "jason.schultz@mailinator.com",
    district: "6",
    county: "Crawford",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "817aab2e-1378-4088-9a3d-26d36f9de520",
    name: "Michael V. Sexton",
    title: null,
    firstName: "Michael",
    middleName: "V.",
    lastName: "Sexton",
    email: "mike.sexton@mailinator.com",
    district: "7",
    county: "Calhoun",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "871bc0b1-d367-4e3d-8206-ae845e33d08a",
    name: "Tom Shipley",
    title: null,
    firstName: "Tom",
    middleName: null,
    lastName: "Shipley",
    email: "tom.shipley@mailinator.com",
    district: "9",
    county: "Adams",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "8c4d9145-105b-417f-9386-9fe24b78bb88",
    name: "Jeff Shipley",
    title: null,
    firstName: "Jeff",
    middleName: null,
    lastName: "Shipley",
    email: "jeff.shipley@mailinator.com",
    district: "87",
    county: "Van Buren",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "8f76fa4c-93c2-4c29-9b4b-06c2bf8b05f8",
    name: "David Sieck",
    title: null,
    firstName: "David",
    middleName: null,
    lastName: "Sieck",
    email: "david.sieck@mailinator.com",
    district: "16",
    county: "Mills",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "d5f2a346-aa5d-4596-8983-c456685238a2",
    name: "Brent Siegrist",
    title: null,
    firstName: "Brent",
    middleName: null,
    lastName: "Siegrist",
    email: "brent.siegrist@mailinator.com",
    district: "19",
    county: "Pottawattamie",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "fcb4e39c-2fd1-4884-950e-4c27ecd48956",
    name: "Amy Sinclair",
    title: null,
    firstName: "Amy",
    middleName: null,
    lastName: "Sinclair",
    email: "amy.sinclair@mailinator.com",
    district: "12",
    county: "Wayne",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "7839217a-c72d-449d-a1fa-9e779b7408cb",
    name: "Dave Sires",
    title: null,
    firstName: "Dave",
    middleName: null,
    lastName: "Sires",
    email: "dave.sires@mailinator.com",
    district: "38",
    county: "Black Hawk",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "58ae3d78-c803-49ba-bc23-1e4f8dba2ff5",
    name: "Travis M. Sitzmann",
    title: null,
    firstName: "Travis",
    middleName: "M.",
    lastName: "Sitzmann",
    email: "travis.sitzmann@mailinator.com",
    district: "13",
    county: "Plymouth",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "71aec881-515e-4879-a359-30a6b39942ac",
    name: "Jennifer J. Smith",
    title: null,
    firstName: "Jennifer",
    middleName: "J.",
    lastName: "Smith",
    email: "jennifer.smith@mailinator.com",
    district: "72",
    county: "Dubuque",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "3c823715-8f8d-4c59-843d-e26f52cdf713",
    name: "Ray Sorensen",
    title: null,
    firstName: "Ray",
    middleName: null,
    lastName: "Sorensen",
    email: "ray.sorensen@mailinator.com",
    district: "23",
    county: "Adair",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "84f9befb-aae5-4c7f-9335-b41509ec5ff6",
    name: "Dr. Megan L. Srinivas",
    title: "Dr.",
    firstName: "Megan",
    middleName: "L.",
    lastName: "Srinivas",
    email: "megan.srinivas@mailinator.com",
    district: "30",
    county: "Polk",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "204cb108-41e4-4091-9995-8533b36f05d2",
    name: "Art Staed",
    title: null,
    firstName: "Art",
    middleName: null,
    lastName: "Staed",
    email: "art.staed@mailinator.com",
    district: "40",
    county: "Linn",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "28a2f6d1-f2ba-45d1-8b7c-f526bcbd4d6e",
    name: "Henry Stone",
    title: null,
    firstName: "Henry",
    middleName: null,
    lastName: "Stone",
    email: "henry.stone@mailinator.com",
    district: "9",
    county: "Winnebago",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "c1c9c4e9-656a-49db-ba23-6a09cc83215c",
    name: "Annette Sweeney",
    title: null,
    firstName: "Annette",
    middleName: null,
    lastName: "Sweeney",
    email: "annette.sweeney@mailinator.com",
    district: "27",
    county: "Hardin",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "fc16c166-b30e-4bd8-9dee-21a92cdf94b7",
    name: "Jeff Taylor",
    title: null,
    firstName: "Jeff",
    middleName: null,
    lastName: "Taylor",
    email: "jeff.taylor@mailinator.com",
    district: "2",
    county: "Sioux",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "7b647313-7e85-46aa-ad1e-67bf99ccd543",
    name: "Mark I. Thompson",
    title: null,
    firstName: "Mark",
    middleName: "I.",
    lastName: "Thompson",
    email: "mark.thompson@mailinator.com",
    district: "56",
    county: "Wright",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "772b6bcd-a5f7-4fda-9316-86864a8baa50",
    name: "Charley Thomson",
    title: null,
    firstName: "Charley",
    middleName: null,
    lastName: "Thomson",
    email: "charley.thomson@mailinator.com",
    district: "58",
    county: "Floyd",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "aeff33a6-870e-44af-9d4c-9d3c023d73d7",
    name: "Thomas Townsend",
    title: null,
    firstName: "Thomas",
    middleName: null,
    lastName: "Townsend",
    email: "thomas.townsend@mailinator.com",
    district: "36",
    county: "Dubuque",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "8883f99d-d205-44d3-bdf8-22f95e86067e",
    name: "Josh Turek",
    title: null,
    firstName: "Josh",
    middleName: null,
    lastName: "Turek",
    email: "josh.turek@mailinator.com",
    district: "20",
    county: "Pottawattamie",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "6b387a1d-a11a-45f5-8d7a-41d717718811",
    name: "Mike Vondran",
    title: null,
    firstName: "Mike",
    middleName: null,
    lastName: "Vondran",
    email: "mike.vondran@mailinator.com",
    district: "94",
    county: "Scott",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "f12dbd6e-0b62-4048-afc9-ef11783b01b7",
    name: "Zach Wahls",
    title: null,
    firstName: "Zach",
    middleName: null,
    lastName: "Wahls",
    email: "zach.wahls@mailinator.com",
    district: "43",
    county: "Johnson",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "c4ba5fc6-6575-4047-9f37-b66652867f6a",
    name: "Kara Warme",
    title: null,
    firstName: "Kara",
    middleName: null,
    lastName: "Warme",
    email: "kara.warme@mailinator.com",
    district: "26",
    county: "Story",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "ee64d6ed-5eda-476a-8e87-947e81e6de7e",
    name: "Blaine C. Watkins",
    title: null,
    firstName: "Blaine",
    middleName: "C.",
    lastName: "Watkins",
    email: "blaine.watkins@mailinator.com",
    district: "100",
    county: "Lee",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "970bf73c-7769-4fc4-90c9-d827e69ce719",
    name: "Scott Webster",
    title: null,
    firstName: "Scott",
    middleName: null,
    lastName: "Webster",
    email: "scott.webster@mailinator.com",
    district: "47",
    county: "Scott",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "5f789768-0386-4acd-87eb-1c844ccc24da",
    name: "Janice Weiner",
    title: null,
    firstName: "Janice",
    middleName: null,
    lastName: "Weiner",
    email: "janice.weiner@mailinator.com",
    district: "45",
    county: "Johnson",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "a6c4d6fa-b38f-41e8-b65a-de4be2ba17bd",
    name: "Ryan Weldon",
    title: null,
    firstName: "Ryan",
    middleName: null,
    lastName: "Weldon",
    email: "ryan.weldon@mailinator.com",
    district: "41",
    county: "Polk",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "23723ba9-ab18-4f12-8680-b5fd14e3cacc",
    name: "Sam Wengryn",
    title: null,
    firstName: "Sam",
    middleName: null,
    lastName: "Wengryn",
    email: "sam.wengryn@mailinator.com",
    district: "24",
    county: "Decatur",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "85aeccf0-985f-4a28-92a7-ddc72e2086bd",
    name: "Beth Wessel-Kroeschell",
    title: null,
    firstName: "Beth",
    middleName: null,
    lastName: "Wessel-Kroeschell",
    email: "beth.wessel-kroeschell@mailinator.com",
    district: "49",
    county: "Story",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "529eb1f2-f755-4067-9147-cc8f3f0d8f54",
    name: "Cherielynn Westrich",
    title: null,
    firstName: "Cherielynn",
    middleName: null,
    lastName: "Westrich",
    email: "cherielynn.westrich@mailinator.com",
    district: "13",
    county: "Wapello",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "6787e902-73dc-45c1-9145-5ab982fa113d",
    name: "Skyler Wheeler",
    title: null,
    firstName: "Skyler",
    middleName: null,
    lastName: "Wheeler",
    email: "skyler.wheeler@mailinator.com",
    district: "4",
    county: "Sioux",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "ef1f4bd6-0c59-4030-a7db-0715f4f28cf3",
    name: "Jack Whitver",
    title: null,
    firstName: "Jack",
    middleName: null,
    lastName: "Whitver",
    email: "jack.whitver@mailinator.com",
    district: "23",
    county: "Polk",
    party: "Republican",
    chamber: "Senate",
  },
  {
    ID: "b7da4819-38ca-4570-9bc6-589bf61dcb87",
    name: "Aime Wichtendahl",
    title: null,
    firstName: "Aime",
    middleName: null,
    lastName: "Wichtendahl",
    email: "aime.wichtendahl@mailinator.com",
    district: "80",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "a882b56a-5f77-48e2-bf0b-cc1f5ebbc957",
    name: "Ross Wilburn",
    title: null,
    firstName: "Ross",
    middleName: null,
    lastName: "Wilburn",
    email: "ross.wilburn@mailinator.com",
    district: "50",
    county: "Story",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "f54eec18-1b5b-4428-b2c0-b8dbcf541757",
    name: "Craig Steven Williams",
    title: null,
    firstName: "Craig",
    middleName: "Steven",
    lastName: "Williams",
    email: "craig.williams@mailinator.com",
    district: "11",
    county: "Carroll",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "f584ac37-3c8f-4a4c-b7e6-a0831e58155d",
    name: "John H. Wills",
    title: null,
    firstName: "John",
    middleName: "H.",
    lastName: "Wills",
    email: "john.wills@mailinator.com",
    district: "10",
    county: "Dickinson",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "4f63eee6-4950-4e19-8b82-a7984a5b0397",
    name: "Elizabeth Wilson",
    title: null,
    firstName: "Elizabeth",
    middleName: null,
    lastName: "Wilson",
    email: "elizabeth.wilson@mailinator.com",
    district: "73",
    county: "Linn",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "ff1315d6-0692-48c2-8da2-594180dce831",
    name: "Hans C. Wilz",
    title: null,
    firstName: "Hans",
    middleName: "C.",
    lastName: "Wilz",
    email: "hans.wilz@mailinator.com",
    district: "25",
    county: "Wapello",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "88848c1c-3850-43ee-b08a-d14b46a785a9",
    name: "Cindy Winckler",
    title: null,
    firstName: "Cindy",
    middleName: null,
    lastName: "Winckler",
    email: "cindy.winckler@mailinator.com",
    district: "49",
    county: "Scott",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "5d26b6b0-8cca-4960-90a7-a3c8e85d1be1",
    name: "Matt W. Windschitl",
    title: null,
    firstName: "Matt",
    middleName: "W.",
    lastName: "Windschitl",
    email: "matt.windschitl@mailinator.com",
    district: "15",
    county: "Harrison",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "a18d4c99-c7bf-4bbe-abea-02f672a9882b",
    name: "Devon Wood",
    title: null,
    firstName: "Devon",
    middleName: null,
    lastName: "Wood",
    email: "devon.wood@mailinator.com",
    district: "17",
    county: "Taylor",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "eb06894c-0ed1-4537-bb48-bb3789b420b4",
    name: "Derek Wulf",
    title: null,
    firstName: "Derek",
    middleName: null,
    lastName: "Wulf",
    email: "derek.wulf@mailinator.com",
    district: "76",
    county: "Black Hawk",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "f53614fe-41a1-4d4e-ae71-e375d8b56651",
    name: "David E. Young",
    title: null,
    firstName: "David",
    middleName: "E.",
    lastName: "Young",
    email: "david.young@mailinator.com",
    district: "28",
    county: "Dallas",
    party: "Republican",
    chamber: "House",
  },
  {
    ID: "70b9b313-fe9b-46ae-a5b5-66465950553d",
    name: "Adam Zabner",
    title: null,
    firstName: "Adam",
    middleName: null,
    lastName: "Zabner",
    email: "adam.zabner@mailinator.com",
    district: "90",
    county: "Johnson",
    party: "Democrat",
    chamber: "House",
  },
  {
    ID: "7e314244-540f-4651-b699-3e1c4ca50ee3",
    name: "Mike Zimmer",
    title: null,
    firstName: "Mike",
    middleName: null,
    lastName: "Zimmer",
    email: "mike.zimmer@mailinator.com",
    district: "35",
    county: "Clinton",
    party: "Democrat",
    chamber: "Senate",
  },
  {
    ID: "378d64b4-e2be-4a88-acab-bd1d11cb36bd",
    name: "Dan Zumbach",
    title: null,
    firstName: "Dan",
    middleName: null,
    lastName: "Zumbach",
    email: "dan.zumbach@mailinator.com",
    district: "34",
    county: "Delaware",
    party: "Republican",
    chamber: "Senate",
  },
];



export default fakeLegislators;